development:
  database: stage_dev
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

test:
  database: stage_test
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000


  